### PR TITLE
Made sure that work with stable rust and updated dependecies

### PR DESCRIPTION
**Pull request by tglman**

### CODE REVIEW

**Comment by mikedilger** [comment]
Thanks.  I haven't been using this library personally for a while so I depend on users to let me know when it needs attention.

I'm cherry-picking over the 'update dependencies' commit.

I agree with the spirit of the other commit - AtomicU8 never stabilized and we should not be on nightly anymore.  However the code changes more things than is strictly necessary for replacing the AtomicU8.  I just pushed another commit to do this more directly.

**Comment by mikedilger** [comment]
Let me know if my recent changes work for you.

**Comment by tglman** [comment]
hi @mikedilger,

Yes the changes work for me, I tryed to update also to the last lettre version but they changed the API of SendableMail introducing the Envelope and some additiona arror management, but mainly the work is all around here : https://github.com/mikedilger/mailstrom/blob/master/src/prepared_email.rs#L124
so probably is not to hard to upgrate to the last version of that.

Regards

**Comment by tglman** [comment]
Hi @mikedilger,

Could we get a public relase compatible with stable ?

Regards

**Comment by mikedilger** [comment]
Sure.
published as 0.5.0

**Pull request closed without merging**
